import SideNav from '@/common/SideNav'
import '@/styles/globals.css'
import { Inter } from 'next/font/google'
import Header from '@/common/Header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" className={inter.className}>
      <body>
        <div className="flex h-screen ">
          {/* @ts-expect-error Async Server Component */}
          <SideNav />
          <div className="w-full ml-[24.4rem]">
            <Header />
            <main className="min-h-[calc(100vh-7.2rem)] mt-[7.2rem] bg-bg-2">{children}</main>
          </div>
        </div>
      </body>
    </html>
  )
}
